In [128]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [129]:
df = pd.read_csv('D:\Hutson\learning-materials\AI&ML\Khóa 12-02AIMLDLCV nâng cao\Class\Datasets\day.csv')
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     731 non-null    int64
 1   dteday      731 non-null    object
 2   season      731 non-null    int64
 3   yr          731 non-null    int64
 4   mnth        731 non-null    int64
 5   holiday     731 non-null    int64
 6   weekday     731 non-null    int64
 7   workingday  731 non-null    int64
 8   weathersit  731 non-null    int64
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  casual      731 non-null    int64
 14  registered  731 non-null    int64
 15  cnt         731 non-null    int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.5+ KB

In [131]:
unused_columns = ['instant', 'dteday', 'casual', 'registered']
df = df.drop(unused_columns, axis=1)
df.head()

,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,985
1,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,801
2,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,1349
3,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,1562
4,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,1600

## Data preprocessing

In [132]:
feature = 'cnt'
x = df.drop(feature, axis=1)
y = df[feature]

In [133]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [134]:
num_transformer = Pipeline(steps=[
    ('num_imputer', SimpleImputer(strategy='median')),
    ('num_scaler', StandardScaler())
])

In [135]:
numeric_columns = x_train.select_dtypes(include=[int, float]).columns
numeric_columns

Index(['season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'temp', 'atemp', 'hum', 'windspeed'],
      dtype='object')

In [136]:
preprocessor = ColumnTransformer(transformers=[
    ("num_features", num_transformer, numeric_columns)]
    )

In [137]:
df

,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,985
1,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,801
2,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,1349
3,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,1562
4,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,1600
...,...,...,...,...,...,...,...,...,...,...,...,...
726,1,1,12,0,4,1,2,0.254167,0.226642,0.652917,0.350133,2114
727,1,1,12,0,5,1,2,0.253333,0.255046,0.590000,0.155471,3095
728,1,1,12,0,6,0,2,0.253333,0.242400,0.752917,0.124383,1341
729,1,1,12,0,0,0,1,0.255833,0.231700,0.483333,0.350754,1796
730,1,1,12,0,1,1,2,0.215833,0.223487,0.577500,0.154846,2729

In [138]:
param_grid =  { 
    'kernel': ['linear', 'rbf'], 
    'C': [0.1, 1, 10], 
    'gamma': [0.1, 1, 10] }

model = GridSearchCV(SVR(), param_grid, cv=5)

reg = Pipeline(steps=[('preprocessor', preprocessor),
                      ('model', LinearRegression())])

reg.fit(x_train, y_train)
y_pred = reg.predict(x_test)

In [139]:
for i, j in zip(y_pred, y_test):
    print("Predicted: ", i, "Actual: ", j)

Predicted:  6220.416612145106 Actual:  6606
Predicted:  1571.6057632139778 Actual:  1550
Predicted:  3043.967028078629 Actual:  3747
Predicted:  4307.202484001378 Actual:  6041
Predicted:  6765.659071662067 Actual:  7538
Predicted:  7231.536105964395 Actual:  7264
Predicted:  774.904146714166 Actual:  1605
Predicted:  2139.6066014898197 Actual:  2209
Predicted:  7112.745605248194 Actual:  7499
Predicted:  6458.992168786488 Actual:  5743
Predicted:  2899.520114198105 Actual:  1796
Predicted:  2118.7822368942975 Actual:  3068
Predicted:  4072.2422231250084 Actual:  4891
Predicted:  5451.212988187958 Actual:  5260
Predicted:  2384.5383859186613 Actual:  2133
Predicted:  2016.2439964955402 Actual:  2471
Predicted:  2383.719503495796 Actual:  2046
Predicted:  7428.59110259186 Actual:  8156
Predicted:  5679.62921960381 Actual:  5362
Predicted:  2937.1022198593246 Actual:  2298
Predicted:  7227.782544192331 Actual:  7697
Predicted:  8234.5057493547 Actual:  5463
Predicted:  5165.556254775544 Actual:  5409
Predicted:  1451.9718410227179 Actual:  1872
Predicted:  1387.0436985190436 Actual:  1807
Predicted:  4823.525098352353 Actual:  5130
Predicted:  1988.7535440636489 Actual:  2121
Predicted:  6734.347400995832 Actual:  7436
Predicted:  4119.29358363765 Actual:  3830
Predicted:  5837.153765251804 Actual:  5557
Predicted:  3036.6642457290973 Actual:  2743
Predicted:  4139.6352813435215 Actual:  3644
Predicted:  5937.431105473441 Actual:  6196
Predicted:  6342.472741268996 Actual:  7494
Predicted:  5404.877124366896 Actual:  5918
Predicted:  4962.58370063058 Actual:  3372
Predicted:  6846.787363179342 Actual:  7582
Predicted:  6131.068505404198 Actual:  6053
Predicted:  3109.8617135356662 Actual:  2566
Predicted:  949.9183577299009 Actual:  1263
Predicted:  4072.373482764953 Actual:  3944
Predicted:  3973.769054823827 Actual:  3956
Predicted:  7237.998390550367 Actual:  7580
Predicted:  3459.285306390996 Actual:  4906
Predicted:  7251.231931731165 Actual:  6966
Predicted:  2229.243805841756 Actual:  705
Predicted:  5162.921022684554 Actual:  4458
Predicted:  5008.885594326144 Actual:  5298
Predicted:  6047.663059966362 Actual:  6043
Predicted:  4162.600626370118 Actual:  4996
Predicted:  3360.0054502043745 Actual:  3351
Predicted:  2748.8562463151648 Actual:  2431
Predicted:  1929.223444902961 Actual:  1011
Predicted:  5832.048671674226 Actual:  4475
Predicted:  4919.076870362313 Actual:  4725
Predicted:  4274.71428393415 Actual:  4727
Predicted:  4355.069765275258 Actual:  2395
Predicted:  2469.631777489499 Actual:  3351
Predicted:  3865.9785462378923 Actual:  4788
Predicted:  6921.22954642497 Actual:  7175
Predicted:  5315.698789225283 Actual:  6153
Predicted:  6640.626211556135 Actual:  7442
Predicted:  2043.8964383566322 Actual:  1471
Predicted:  7029.977046716396 Actual:  7865
Predicted:  6013.411942666803 Actual:  6530
Predicted:  7244.540426960693 Actual:  6211
Predicted:  7234.254151197871 Actual:  7403
Predicted:  5397.0784574498675 Actual:  4302
Predicted:  1749.505457311146 Actual:  2077
Predicted:  6367.304908356509 Actual:  7333
Predicted:  2986.5513190046395 Actual:  3117
Predicted:  2484.8776189051387 Actual:  1635
Predicted:  3191.901833482142 Actual:  3811
Predicted:  3946.350898754098 Actual:  4595
Predicted:  4635.36527091457 Actual:  4363
Predicted:  2747.012763327575 Actual:  2034
Predicted:  5341.457182614904 Actual:  5686
Predicted:  4107.4974616312775 Actual:  4748
Predicted:  1196.1006501246338 Actual:  1416
Predicted:  5154.723132583513 Actual:  4401
Predicted:  2552.607537964468 Actual:  2114
Predicted:  2533.1376006142427 Actual:  2028
Predicted:  5912.465403784788 Actual:  5668
Predicted:  4270.533607919301 Actual:  22
Predicted:  3842.2038291454774 Actual:  3940
Predicted:  4285.347855044698 Actual:  4118
Predicted:  4504.621394890918 Actual:  5423
Predicted:  3450.4736817929643 Actual:  1495
Predicted:  3721.7608261629302 Actual:  3620
Predicted:  3135.471468108479 Actual:  3403
Predicted:  819.5580413942625 Actual:  1501
Predicted:  7129.657120833443 Actual:  7040
Predicted:  5924.697088864697 Actual:  5992
Predicted:  5173.568209336487 Actual:  4990
Predicted:  3182.322792234767 Actual:  3095
Predicted:  3469.0697055518212 Actual:  2832
Predicted:  4744.962760270615 Actual:  4713
Predicted:  2771.1340364807465 Actual:  2368
Predicted:  3036.8463194799947 Actual:  3409
Predicted:  5335.284123168092 Actual:  4991
Predicted:  7446.187406377434 Actual:  7713
Predicted:  4863.444281152163 Actual:  3785
Predicted:  5931.063217365154 Actual:  6664
Predicted:  2665.9853645780568 Actual:  2496
Predicted:  2243.371253869519 Actual:  2077
Predicted:  5623.171367072389 Actual:  5267
Predicted:  1125.1017747888595 Actual:  1162
Predicted:  2478.103766035151 Actual:  2739
Predicted:  7495.56971424814 Actual:  6861
Predicted:  1129.5574692796235 Actual:  1360
Predicted:  5531.8108490027125 Actual:  4602
Predicted:  6351.7767271347275 Actual:  7282
Predicted:  3272.101042200953 Actual:  3570
Predicted:  6745.136175050833 Actual:  8167
Predicted:  5328.564140847583 Actual:  6230
Predicted:  3332.313461439373 Actual:  4511
Predicted:  1605.1504506283268 Actual:  1461
Predicted:  4382.845467143304 Actual:  3272
Predicted:  5084.794801580546 Actual:  5923
Predicted:  3427.516911960104 Actual:  2177
Predicted:  5817.964051934917 Actual:  6398
Predicted:  2850.127049974688 Actual:  1817
Predicted:  3585.902868699614 Actual:  3239
Predicted:  1512.9108249543951 Actual:  1349
Predicted:  4351.940537933215 Actual:  3867
Predicted:  5962.891638441552 Actual:  5146
Predicted:  5628.684924266808 Actual:  4541
Predicted:  2973.7505861357604 Actual:  3368
Predicted:  2193.9224387594604 Actual:  2134
Predicted:  6029.756549292577 Actual:  7410
Predicted:  3212.8129754736747 Actual:  3331
Predicted:  4123.997926141286 Actual:  3974
Predicted:  5390.513216958587 Actual:  5495
Predicted:  4879.943165107163 Actual:  5319
Predicted:  4947.244595419556 Actual:  5895
Predicted:  1889.478319944547 Actual:  2227
Predicted:  5005.8529450666665 Actual:  4367
Predicted:  5880.58423085325 Actual:  7460
Predicted:  1598.3021208747905 Actual:  1977
Predicted:  5384.537350383721 Actual:  4266
Predicted:  3831.2533205262134 Actual:  4864
Predicted:  2362.124045395105 Actual:  1913
Predicted:  2315.142869175693 Actual:  2132
Predicted:  5570.82424966264 Actual:  4258
Predicted:  4168.334567633721 Actual:  2792
Predicted:  4420.697508915733 Actual:  5180
Predicted:  3891.9433526439666 Actual:  3958

In [140]:
### r2 score is most common metric for regression (the higher the better)
print(reg.score(x_test, y_test))

0.8276670090367212